oro_menu_config:
  items:
    titles_managment:
      label: 'Должности'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_titles'
    worktype_management:
      label: 'Типы работ и ставки'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_worktype'
    registration:
      label: 'Регистрация'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_Registration'
      extras:
        position: 40
    project:
      label: 'Проекты'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_Project'
      extras:
        position: 50
    court:
      label: 'Судебные дела'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_Court'
      extras:
        position: 51
    courtinstance:
      label: 'Суды'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_CourtInstance'
      extras:
        position: 52
    clients_tab:
      label: 'Клиенты'
      uri: '#'
      extras:
        position: 3
    clients:
      label: 'Клиенты'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_client'
      extras:
        routes: ['/^Extend_Entity_client/']
    table_calendar:
      label: 'Табель Календарь'
      uri: '#'
      aclResourceId: oro_system_calendar_view
      extras:
        position: 2
    system_tab:
      extras:
        position: 170
    activities_tab:
      extras:
        position: 1
    reports_tab:
      label: 'Отчеты'
      aclResourceId: oro_report_create
      extras:
        position: 4
    month_report:
      label: 'Ежемесячный отчет'
      route: 'nb_report_index'
      routeParameters:
        id: 1
  tree:
    application_menu:
      children:
        clients_tab:
          children:
            clients: ~
        table_calendar:
        activities_tab:
          children:
            registration: ~
            project: ~
            court: ~
            courtinstance: ~
        reports_tab:
          merge_strategy: replace
          children:
            month_report: ~
        system_tab:
          children:
            users_management:
              children:
                titles_managment: ~
                worktype_management: ~