oro_menu_config:
  items:
    titles_managment:
      label: 'Должности'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_titles'
    worktype_management:
      label: 'Типы работ и ставки'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_worktype'
    registration:
      label: 'Регистрация'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_Registration'
      extras:
        position: 40
    project:
      label: 'Проекты'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_Project'
      extras:
        position: 50
    court:
      label: 'Судебные дела'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_Court'
      extras:
        position: 51
    courtinstance:
      label: 'Суды'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_CourtInstance'
      extras:
        position: 52
    clients_tab:
      label: 'Клиенты'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_client'
      extras:
        routes: ['/^Extend_Entity_client/']
        position: 3
    system_tab:
      aclResourceId: oro_report_create
      extras:
        position: 170
    activities_tab:
      display: false
      extras:
        position: 1
    reports_tab:
      label: 'Отчеты'
      aclResourceId: oro_report_create
      extras:
        position: 8
    month_report:
      label: 'Ежемесячный отчет'
      route: 'nb_report_index'
      routeParameters:
        id: 1
    hourly_report:
      label: 'Договор с почасовой оплатой'
      route: 'nb_report_index'
      routeParameters:
        id: 2
    project_report:
      label: 'Отчет по проекту'
      route: 'nb_report_index'
      routeParameters:
        id: 3
    court_report:
      label: 'Отчет по судебному делу'
      route: 'nb_report_index'
      routeParameters:
        id: 4
    oro_system_calendar_list:
      display: false
    table_calendar:
      label: 'Табель-календарь'
      aclResourceId: oro_system_calendar_view
      route: 'nb_table_index'
      extras:
        position: 2
    users:
      label: Сотрудники
      route: 'oro_user_index'
      extras:
        position: 3
    calendar_tab:
      label: Календарь
      uri: '#'
      extras:
        position: 5
    calendar:
      label: Календарь
      route: 'oro_calendar_view_default'
      extras:
        position: 4
    category_tab:
      label: 'Категории дел'
      uri: '#'
      extras:
        position: 6
  tree:
    application_menu:
      children:
        workunit_create: ~
        clients_tab: ~
        users: ~
        calendar_tab:
          children:
            table_calendar: ~
            calendar: ~
        category_tab:
          children:
            workunit_list: ~
            registration: ~
            project: ~
            court: ~
            courtinstance: ~
        reports_tab:
          merge_strategy: replace
          children:
            month_report: ~
            hourly_report: ~
            project_report: ~
        system_tab:
          children:
            users_management:
              children:
                titles_managment: ~
                worktype_management: ~