oro_menu_config:
  items:
    titles_managment:
      label: 'Должности'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_titles'
    worktype_management:
      label: 'Типы работ и ставки'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_worktype'
    registration:
      label: 'Регистрация'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_Registration'
      extras:
        position: 40
    project:
      label: 'Проекты'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_Project'
      extras:
        position: 50
    clients_tab:
      label: 'Клиенты'
      uri: '#'
    clients:
      label: 'Клиенты'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_client'
      extras:
        routes: ['/^Extend_Entity_client/']
  tree:
    application_menu:
      children:
        clients_tab:
          children:
            clients: ~
        activities_tab:
          children:
            registration: ~
            project: ~
        system_tab:
          children:
            users_management:
              children:
                titles_managment: ~
                worktype_management: ~