oro_menu_config:
  items:
    titles_managment:
      label: 'Должности'
      route: 'oro_entity_index'
      routeParameters:
        entityName: 'Extend_Entity_titles'
  tree:
    application_menu:
      children:
        system_tab:
          children:
            users_management:
              children:
                titles_managment: ~