services:
  nb_user.form.type.worktype:
    class: NB\UserBundle\Form\Type\WorkTypeFormType
    arguments: [ @doctrine.orm.entity_manager, @logger ]
    tags:
      - { name: form.type, alias: 'nb_work_type'}
  nb.entity_action_mapper:
    class: NB\UserBundle\RouteHelper\EntityActionMapper
  nb.listener.controller_init:
    class: NB\UserBundle\EventListener\ControllerInitListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }