services:
  nb_user.form.type.worktype:
    class: NB\UserBundle\Form\Type\WorkTypeFormType
    arguments: [ @doctrine.orm.entity_manager, @logger ]
    tags:
      - { name: form.type, alias: 'nb_work_type'}
  nb.entity_action_mapper:
    class: NB\UserBundle\RouteHelper\EntityActionMapper