datagrid:
    workunit-grid:
        extended_entity_name: %nb_workunit.entity.class%
        source:
            type: orm
            acl_resource: nb_workunit_view
            query:
                select:
                    - workunit.id
                    - workunit.subject
                    - workunit.startDate
                    - workunit.endDate
                    - worktype.name as worktypeName
                    - workunit.contract
                    - client.name as clientName
                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as ownerName
                    - owner.id as ownerId
                from:
                    - { table: %nb_workunit.entity.class%, alias: workunit }
                join:
                    left:
                        - { join: workunit.worktype, alias: worktype }
                        - { join: workunit.owner, alias: owner }
                        - { join: workunit.client, alias: client }
        columns:
            startDate:
                label:         Начало
                frontend_type:          datetime
            endDate:
                label:         Окончание
                frontend_type:          datetime
            worktypeName:
                label:         Тип работы
            contract:
                label:         Договор
                type:          callback
                callable:      NB\ReportBundle\Model\ContractContainer::datagridLabel
            subject:
                label:         nb.wu.subject.label
            ownerName:
                label:         Юрист
            clientName:
                label:         Клиент
        sorters:
            columns:
                startDate:
                    data_name: workunit.startDate
                endDate:
                    data_name: workunit.endDate
                worktypeName:
                    data_name: worktypeName
                contract:
                    data_name: contract
                ownerName:
                    data_name: ownerName
                clientName:
                    data_name: clientName
                contract:
                    data_name: contract
            default:
                startDate: ASC
        filters:
            columns:
                startDate:
                    type: datetime
                    data_name: workunit.startDate
                endDate:
                    type: datetime
                    data_name: workunit.endDate
                worktypeName:
                    type:      string
                    data_name: worktypeName
                client:
                    type:      string
                    label: Клиент
                    data_name: clientName
                ownerName:
                    type:      string
                    data_name: ownerName
            default:
                startDate:
                    value: { start: '{{2}}' }
                    part: Oro\Bundle\FilterBundle\Provider\DateModifierInterface::PART_VALUE
                    type: Oro\Bundle\FilterBundle\Form\Type\Filter\DateRangeFilterType::TYPE_MORE_THAN
        properties:
            id: ~
            view_link:
                type:       url
                route:      nb_workunit_view
                params:     [ id ]
            update_link:
                type:       url
                route:      nb_workunit_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      nb_api_delete_workunit
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  nb_workunit_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  nb_workunit_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  nb_workunit_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
        options:
            entity_pagination: true
    grid-report-monthly:
        options:
            entity_pagination: true
            skip_acl_check: true
        extended_entity_name: %nb_workunit.entity.class%
        source:
            type: orm
            query:
                select:
                    - workunit.id
                    - workunit.subject
                    - workunit.startDate
                    - workunit.endDate
                    - worktype.name as worktypeName
                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as ownerName
                    - title.name as titleName
                from:
                    - { table: %nb_workunit.entity.class%, alias: workunit }
                join:
                    left:
                        - { join: workunit.worktype, alias: worktype }
                        - { join: workunit.owner, alias: owner }
                        - { join: workunit.client, alias: client }
                        - { join: owner.custom_title, alias: title }
                where:
                    and:
                        - client.id = :clientId
                        - workunit.contract = :contractId
        columns:
            startDate:
                label:         Начало
                frontend_type:          datetime
            endDate:
                label:         Окончание
                frontend_type:          datetime
            ownerName:
                label:         Юрист
            titleName:
                label:         Должность
            worktypeName:
                label:         Тип работы
            subject:
                label:         nb.wu.subject.label
        sorters:
            columns:
                startDate:
                    data_name: workunit.startDate
            default:
                startDate: ASC
        filters:
            columns:
                startDate:
                    type: datetime
                    data_name: workunit.startDate
                endDate:
                    type: datetime
                    data_name: workunit.endDate
                worktypeName:
                    type:      string
                    data_name: worktypeName
                ownerName:
                    type:      string
                    data_name: ownerName
                titleName:
                    type:      string
                    data_name: titleName