oro_menu_config:
    items:
        workunit_list:
            label: 'nb.wu.entity_plural_label'
            route: 'nb_workunit_index'
            extras:
                position: 1
                routes: ['nb_workunit_update', 'nb_workunit_view']
                description: ''
        workunit_create:
            label: 'Заполнить отчет'
            route: 'nb_workunit_create'
            extras:
                position: 1

oro_titles:
    nb_workunit_index: 'Текущие дела'
    nb_workunit_view: 'Просмотреть отчет'
    nb_workunit_create: oro.ui.create_entity
    nb_workunit_update: 'Редактировать отчет о работе'
