NB\ReportBundle\Entity\WorkUnit:
    properties:
        startDate:
            - NotBlank: ~
            - DateTime: ~
        endDate:
            - DateTime: ~
        worktype:
            - NotBlank: ~
        owner:
            - NotBlank: ~
        client:
            - NotBlank: ~
        subject:
            - Length:
                max: 255