datagrid:
    custom-entity-grid:
        options:
            base_datagrid_class: Oro\Bundle\EntityBundle\Grid\CustomEntityDatagrid
            entityHint: entity
            export: true
            entity_pagination: true
        source:
            acl_resource: ~
            type: orm
            query:
                select:
                    - ce.id
                from:
                    - { table: ENTITY_NAME, alias: ce }
                leftJoin:
                    - { table: }
        columns: # no static columns
            id: {renderable: false} #required because of OrmSorterExtension
        properties:
            id: ~
            update_link:
                type: callback
                callable: @oro_entity.event_listener.custom_entity_grid_listener->getLinkProperty
                route: oro_entity_update
                params:
                    - id
            view_link:
                type: callback
                callable: @oro_entity.event_listener.custom_entity_grid_listener->getLinkProperty
                route: oro_entity_view
                params:
                    - id
            delete_link:
                type: callback
                callable: @oro_entity.event_listener.custom_entity_grid_listener->getLinkProperty
                route: oro_entity_delete
                params:
                    - id
        actions:
            # TODO: add dynamic acl_resources
            view:
                type: navigate
                label: oro.grid.action.view
                icon: eye-open
                link: view_link
                rowAction: true
            update:
                type: navigate
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                type: delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        sorters:
            columns:
                id:
                    data_name: ce.id
        filters:
            columns: []

    entity-relation-grid:
        options:
            entityHint: entity
            routerEnabled: false
            rowSelection:
                dataField: id
                columnName: assigned
                selectors:
                    included: '#appendRelation'
                    excluded: '#removeRelation'
        source:
            acl_resource: ~
            type: orm
        columns:
            assigned:
                frontend_type: boolean
                label: oro.entity.datagrid.assigned
                editable: true
        properties:
            id: ~
        sorters:
            columns:
                assigned:
                    data_name: assigned
            default:
                assigned: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
        filters:
            columns:
                assigned:
                    type: boolean
                    data_name: assigned
                    filter_by_having: true
