services:
    nb.acl.collab_voter:
        class:      NB\CoreBundle\Acl\Voter\CollaborationVoter
        public:     false
        arguments:  [@oro_entity_config.provider.entity, @oro_entity.doctrine_helper, @logger]
    nb.object_acl_manager:
      class: NB\CoreBundle\Security\ObjectAclManager
      arguments: [@oro_security.acl.manager, @logger]
    nb.collab_acl_subscriber:
      class: NB\CoreBundle\EventListener\CollaborationAclSubscriber
      arguments: [ @service_container ]
      tags:
        - { name: doctrine.event_subscriber }
    nb.event_listener.collab_grid_listener:
      class: NB\CoreBundle\EventListener\CollaborationDatagridListener
      arguments:  
        -  @oro_entity_config.provider.entity
        -  @security.context
        -  @?security.acl.voter.basic_permissions
        -  @oro_security.acl_helper
      tags:
        - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.custom-entity-grid, method: onBuildAfter, priority: -255 }
        - { name: kernel.event_listener, event: oro_datagrid.datagrid.result.before.custom-entity-grid, method: onResultBefore }