datagrid:
    court-grid:
        extended_entity_name: %nb_workunit.entity.class%
        source:
            type: orm
            acl_resource: oro_entity_view
            query:
                select:
                    - court.id
                    - court.name
                    - court.result
                    - courtInstance.name as courtInstanceName
                    - client.name as clientName
                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as ownerName
                    - owner.id as ownerId
                from:
                    - { table: Extend\Entity\Court, alias: court }
                join:
                    left:
                        - { join: court.courtCurrent, alias: courtInstance }
                        - { join: court.owner, alias: owner }
                        - { join: court.client, alias: client }
        columns:
            name:
                label:         Номер дела
            clientName:
                label:         Клиент
            courtInstanceName:
                label:         Суд
            result:
                label:         Результат
        sorters:
            columns:
                name:
                    data_name: court.name
                clientName:
                    data_name: clientName
                courtInstanceName:
                    data_name: courtInstanceName
                result:
                    data_name: court.result
            default:
                name: ASC
        filters:
            columns:
                name:
                    type: string
                    data_name: court.name
                clientName:
                    type: string
                    label: Клиент
                    data_name: clientName
                courtInstanceName:
                    type: string
                    data_name: courtInstanceName
                    label: Суд
                result:
                    type: string
                    data_name: court.result
        properties:
            id: ~
            update_link:
                type: callback
                callable: @nb_court.event_listener.datagrid_listener->getLinkProperty
                route: oro_entity_update
                params:
                    - id
            view_link:
                type: callback
                callable: @nb_court.event_listener.datagrid_listener->getLinkProperty
                route: oro_entity_view
                params:
                    - id
            delete_link:
                type: callback
                callable: @nb_court.event_listener.datagrid_listener->getLinkProperty
                route: oro_entity_delete
                params:
                    - id
        actions:
            # TODO: add dynamic acl_resources
            view:
                type: navigate
                label: oro.grid.action.view
                icon: eye-open
                link: view_link
                rowAction: true
            update:
                type: navigate
                label: oro.grid.action.update
                icon: edit
                link: update_link
            delete:
                type: delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link
        options:
            entity_pagination: true
            skip_acl_check: true