services:
  nb_court.event_listener.datagrid_listener:
    class: NB\CourtBundle\EventListener\DatagridListener
    arguments:
      - @router
      -  @security.context
      -  @?security.acl.voter.basic_permissions
    tags:
        - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.court-grid, method: onBuildAfter }
  nb_court.doctrine_subscriber:
      class: NB\CourtBundle\EventListener\CourtDoctrineSubscriber
      tags:
        - { name: doctrine.event_subscriber }
  nb.form.type.feed:
    class: NB\CourtBundle\Form\Type\FeedType
    tags:
      - { name: form.type, alias: nb_feed_form }
  nb_court.activity_list.provider:
    class: NB\CourtBundle\Provider\FeedActivityListProvider
    arguments:
       - @oro_entity.doctrine_helper
    tags:
       - {name: oro_activity_list.provider, priority: 10}