orocrm_task_bundle:
    resource:     "@OroCRMTaskBundle/Controller"
    type:         annotation
    prefix:       /

orocrm_task_bundle_api:
    resource:     "@OroCRMTaskBundle/Controller/Api/Rest/TaskController.php"
    type:         rest
    prefix:       api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest

# deprecated API route
orocrm_api_post_task_deprecated:
    path:            /api/rest/{version}/task.{_format}
    methods:         [POST]
    defaults:
        _controller: OroCRM\TaskBundle\Controller\Api\Rest\TaskController::postAction
        _format:     json
        version:     latest
    requirements:
        _format:     json|html
        version:     latest|v1
