workflows:
    task_flow:
        steps:
            open:
                label: 'Открыта'
                order: 10
                allowed_transitions:
                    - start_progress
                    - close
            in_progress:
                label: 'Принята к исполнению'
                order: 20
                allowed_transitions:
                    - stop_progress
                    - close
            closed:
                label: 'Выполнена'
                order: 30
                allowed_transitions:
                    - reopen
