workflows:
    task_flow:
        transitions:
            start_progress:
                label: 'Start progress'
                step_to: in_progress
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-play'
                transition_definition: start_progress_definition
            stop_progress:
                label: 'Stop progress'
                step_to: open
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-stop'
                transition_definition: stop_progress_definition
            close:
                label: 'Close'
                step_to: closed
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-ok'
                transition_definition: closed_definition
            reopen:
                label: 'Reopen'
                step_to: open
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-edit'
                transition_definition: reopen_definition
